name: Synchronize with the upstream

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  synchronize:
    name: "Synchronize with the upstream"
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - run: |
          set -xeuo pipefail
          git remote add upstream https://github.com/ligato/vpp-agent.git
          git fetch upstream
          for branch in master dev; do
            git checkout -b upstream-${branch} --track origin/upstream-${branch}
            git reset --hard upstream/${branch}
            git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          done
      - name: Post notification to Slack if failed
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: squad-dp
          status: FAILED
          color: danger
